### PR TITLE
Overlap PR0

### PR DESCRIPTION
**Pull request by ramirezfranciscof**
* Created liosubs_math to hold all generic math subroutines and interfaces (what I first tried with mathsubs but didn't finish. Also, mathsubs is f77, eventually it should disappear)
* Created typedef_sop to hide all related to the overlap operator inside a predefined type/class.
* Replaced overlap_diag with the newly defined type.

Current status: it should run normally with cholesky. I tried lowdin/canonical diagonalizations but don't work yet. In order to fix this I would need to touch a little bit SCF so I wanted to send in this changes first, please check that no previous functionality is broken.

### CODE REVIEW

**Comment by ramirezfranciscof** [comment]
@charlyqchm I know you are doing stuff. Check this.

**Comment by fedepedron** [comment]
I'll be testing this during the weekend for additional checks. But @charlyqchm should do his magic.

**Comment by charlyqchm** [comment]
Sorry for the delay. is it necessary that I test this yet?

2018-01-07 12:33 GMT-03:00 Federico N. Pedron <notifications@github.com>:

**Comment by ramirezfranciscof** [comment]
@charlyqchm Yes. Essential. A matter of life or death for the whole humanity.

**Comment by charlyqchm** [comment]
OMG, I don't know if I can manage this responsibility XD

2018-01-08 12:09 GMT-03:00 ramirezfranciscof <notifications@github.com>:

**Comment by ramirezfranciscof** [comment]
@charlyqchm Do not misinterpret the joking as leeway to not do this.

**Comment by charlyqchm** [comment]
Sorry, I didn't misinterpret it as a joke, I just forgot it jeje. I tested with cuda and intel, there is no problem with SCF nor Transport. Nevertheless, with the compilation options cuda=2 and intel=2, it took a long time to compile faint_cpu77.f. Wasn't this problem already solved?

**Comment by ramirezfranciscof** [comment]
@charlyqchm Are you sure you are compiling the right branch? I just tried what you said and even though it seems compilation takes a little longer with those options, I see it take longer an all objects. In particular, I also see the compilation of all int submodules separatedly and the specific object faint_cpu77.o compiles instantly.

**Pull request merged**
