### PR TITLE
Geometry Optimization

### PR DESCRIPTION
**Pull request by Nick-Chaos**
A steepest-descend algorithm for geometry optimizations was added to lio code. Variables for use it and algorithm scheme was added to manual.
The code was tested with ifort and gfortran, only with liosolo.
Modifications was done over Ehrenfest Beta pull-request.

### CODE REVIEW

**Comment by ramirezfranciscof** [comment]
@Nick-Chaos Your branch diverged from rc when I squashed ehrenfest PR. I have rebased locally and once I skipped the first patch, all your commits where automatically applied. If you wish to [try rebasing](https://github.com/MALBECC/lio/wiki/Development-Workflow#updating-changes) yourself this case should go quite smoothly (we can do it together). If not, I can force push my version to your fork, and you can update your local repo and test that everything is ok.

**Comment by ramirezfranciscof** [comment]
I rebased the branch and now is again ready to be squashed. Please do check that the patches have been reapplied correctly.

**Comment by fedepedron** [comment]
Cannot compile due to ehrenfest.mod missing from some files. This needs to be corrected by adding "SCF_exter.o init_lio.o liomain.o" to line 103 of lioamber/Makefile.depends .

**Comment by fedepedron** [comment]
Tested with gfortran both gpu and cpu, and with Gromacs. All good.

**Pull request merged**
