### PR TITLE
New interface with Hybrid

### PR DESCRIPTION
**Pull request by gonzalodm**
A little modification in Hybrid interface.

### CODE REVIEW

**Comment by fedepedron** [comment]
Everything seems alright, is this compatible with the newest version of hybrid?

**Comment by gonzalodm** [comment]
Not yet, but nick and jota are checking the PR in HYB

**Comment by fedepedron** [comment]
Ok then, merge this when that is resolved, so that everything gets done simulatenously.

**Comment by Nick-Chaos** [comment]
Mergeo los 2 a la vez entonces cuando terminemos de probar todo

**Pull request closed without merging**
